version: '3'

services:

  app: 
    build: 
      context: .
    ports:
      - 3000:3000
    entrypoint: wait-for database:3306 -t 40 -- ./entrypoint.sh
    volumes:
      - ./:/home/node/app
    depends_on:
      - database

  database:
    image: mysql:5.7
    restart: always
    tty: true
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=nodedb